// Run: node lab/check.cjs (uses the installed Google Chrome; no packages needed).
const fs=require('fs'),os=require('os'),path=require('path'),{execFileSync}=require('child_process');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lab-check-'));
const test=`<script>
try {
const assert=(ok,msg)=>{if(!ok)throw Error(msg)};
const target=()=>document.querySelector('.next-target')?.dataset.place;assert(target()==='bench','initial target');
openPlace('door');assert(!state.escaped,'door must start locked');$('modal').close();
openPlace('cabinet');assert(!$('unlock'),'cabinet must require clues');$('modal').close();
openPlace('bench');$('mix').click();assert(!state.mixed,'empty mix fails');
document.querySelector('[data-color="红"]').click();document.querySelector('[data-color="蓝"]').click();$('mix').click();assert(!state.mixed,'wrong mix fails');
document.querySelector('[data-color="红"]').click();document.querySelector('[data-color="黄"]').click();$('mix').click();assert(state.mixed,'green reveals card');assert(target()==='board','next target board');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='board','next button focuses board');
openPlace('board');$('answer').value='111';$('decode').dispatchEvent(new Event('submit',{cancelable:true}));assert(!state.decoded,'wrong symbols fail');$('answer').value='472';$('decode').dispatchEvent(new Event('submit',{cancelable:true}));assert(state.decoded,'symbols solved');assert(target()==='cabinet','next target cabinet');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='cabinet','next button focuses cabinet');
openPlace('cabinet');$('code').value='472';$('unlock').dispatchEvent(new Event('submit',{cancelable:true}));assert(!state.key,'unreversed code fails');$('code').value='274';$('unlock').dispatchEvent(new Event('submit',{cancelable:true}));assert(state.cabinet&&!state.key,'reversed code gets battery');assert(target()==='circuit','next target circuit');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='circuit','next button focuses circuit');
openPlace('circuit');$('power').click();assert(!state.powered,'wrong circuit fails');document.querySelector('[data-switch="0"]').click();document.querySelector('[data-switch="2"]').click();$('power').click();assert(state.powered,'circuit powered');assert(target()==='scope','next target scope');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='scope','next button focuses scope');
openPlace('scope');document.querySelector('[data-pattern="a"]').click();assert(!state.observed,'wrong pattern fails');document.querySelector('[data-pattern="b"]').click();assert(state.observed,'pattern solved');assert(target()==='robot','next target robot');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='robot','next button focuses robot');
openPlace('robot');document.querySelector('[data-symbol="★"]').click();assert(!state.key,'wrong sequence fails');for(const symbol of ['☀','☾','★'])document.querySelector('[data-symbol="'+symbol+'"]').click();assert(state.key,'sequence gets key');assert(target()==='door','next target door');assert($('goNext'),'success next button');$('goNext').click();assert(!$('modal').open&&document.activeElement.dataset.place==='door','next button focuses door');
openPlace('door');assert(state.escaped,'escape complete');assert(!target()&&$('locateNext').hidden,'guide cleared on escape');$('again').click();assert(!state.mixed&&!state.decoded&&!state.key&&!state.cabinet&&!state.powered&&!state.observed&&!state.escaped,'restart clears state');assert(target()==='bench'&&!$('locateNext').hidden,'guide reset');
$('hint').click();assert(state.hints===1,'hint works');assert(document.documentElement.scrollWidth<=innerWidth,'no horizontal overflow');
document.querySelectorAll('[data-place]').forEach(b=>{const r=b.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);assert(b.contains(hit),'click region blocked: '+b.dataset.place)});
document.body.innerHTML='<p>CHECK_PASS: locked states, wrong answers, six puzzles, escape, restart, hints, viewport, object hit areas, target guidance</p>';
}catch(e){document.body.innerHTML='<p>CHECK_FAIL: '+e.message+'</p>'}
parent.postMessage(document.body.textContent,'*');
</script>`;
fs.writeFileSync(path.join(dir,'test.html'),fs.readFileSync(path.join(__dirname,'index.html'),'utf8').replace('<link rel="stylesheet" href="visual.css">','<style>'+fs.readFileSync(path.join(__dirname,'visual.css'),'utf8')+'</style>').replace('</body>',test+'</body>'));
const source=fs.readFileSync(path.join(dir,'test.html'),'utf8');
try{for(const size of ['1280,900','390,844']){fs.writeFileSync(path.join(dir,'viewport.html'),'<body style="margin:0"><script>onmessage=e=>document.body.textContent=e.data<'+"/script>"+'<iframe style="border:0;width:'+size.split(',')[0]+'px;height:1200px" srcdoc="'+source.replace(/&/g,'&amp;').replace(/"/g,'&quot;')+'"></iframe>');let out;try{out=execFileSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--user-data-dir='+path.join(dir,'profile-'+size),'--window-size='+size,'--dump-dom','file://'+path.join(dir,'viewport.html')],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:10000});}catch(e){if(e.code!=='ETIMEDOUT')throw e;out=String(e.stdout||'')}if(!out.includes('CHECK_PASS:'))throw Error(out);console.log(size+': '+out.match(/CHECK_PASS:[^<]+/)[0])}}finally{fs.rmSync(dir,{recursive:true,force:true})}
